import React from 'react'
import NavBar from './NavBar'
import './experianTerms.css'
import NewHomePageFooter from './NewHomePageFooter'

const ExperianTerms = () => {
        return (
            <>
                <div>
                    <NavBar />
                </div>
                <div className="experian-e-container">
                    <div className="text-sect-e">
                        <h1>Experian <span style={{ color: "#3e2780" }}>terms of service</span></h1>
                    </div>
                </div>

                <div className='Content-sect-exp' style={{ padding: "20px" }}>
                <div className="content-of-exp-terms">
                    <h2>Consent in relation to access to credit information through experian</h2>
                    <p>This end user agreement (the “Agreement”) is made between you (the “User” or “You”) and Vibhuprada Services Pvt Ltd (herein reffered to as CreditHaat), a private limited company having its registered office at 7 to 12, 7th Floor, Building-B, Downtown City vista, kharadi Pune, India - 411014. (“CreditHaat”, “Us” or “We”, which term shall include its successors and permitted assigns). The User and CreditHaat shall be collectively referred to as the “Parties” and individually as a “Party”.</p>
                    <p>You hereby consent to CreditHaat being appointed as your authorised representative to receive your Credit Information from Experian for the purpose of accessing credit worthiness and availing pre-approved offers (“End Use Purpose”).</p>
                    <p>BY EXECUTING THIS AGREEMENT / CONSENT FORM, YOU ARE EXPRESSLY AGREEING TO ACCESS THE EXPERIAN CREDIT INFORMATION REPORT AND CREDIT SCORE, AGGREGATE SCORES, INFERENCES, REFERENCES AND DETAILS (AS DEFINED BELOW) (TOGETHER REFERRED AS “CREDIT INFORMATION”). YOU HEREBY ALSO CONSENT TO SUCH CREDIT INFORMATION BEING PROVIDED BY EXPERIAN TO YOU AND CREDITHAAT BY USING EXPERIAN TOOLS, ALGORITHMS AND DEVICES AND YOU HEREBY AGREE, ACKNOWLEDGE AND ACCEPT THE TERMS AND CONDITIONS SET FORTH HEREIN.</p>
                    <h2>Terms and conditions :</h2>
                    <p>Information Collection, Use, Confidentiality, No-Disclosure and Data Purging</p>
                    <p>CreditHaat shall access your Credit Information as your authorized representative and CreditHaat shall use the Credit Information for limited End Use Purpose consisting of and in relation to the services proposed to be availed by you from CreditHaat. We shall not aggregate, retain, store, copy, reproduce, republish, upload, post, transmit, sell or rent the Credit Information to any other person and the same cannot be copied or reproduced other than as agreed herein and in furtherance to applicable law including the CICRA.</p>
                <p>The Parties agree to protect and keep confidential the Credit Information both online and offline.</p>
                <p>The Credit Information shared by you, or received on by us on your behalf shall be destroyed, purged, erased immediately upon the completion of the transaction/ End Use Purpose for which the Credit Information report was procured, this period not being longer than 6 months.</p>
                </div>
                <div className="content-of-exp-terms">
                    <h2>Governing law and jurisdiction :</h2>
                    <p>The relationship between you and CreditHaat shall be governed by laws of India and all claims or disputes arising there from shall be subject to the exclusive jurisdiction of the courts of Mumbai.</p>
                    </div>
                <div className="content-of-exp-terms">
                    <h2>Definitions :</h2>
                    <p>Capitalised terms used herein but not defined above shall have the following meanings:</p>

                </div>
                <div className="content-of-exp-terms">
                    <h2>Business day</h2>
                    <p>means a day (other than a public holiday) on which banks are open for general business in Mumbai.</p>

                </div>
                <div className="content-of-exp-terms">
                    <h2>Credit information report</h2>
                    <p>means the credit information / scores/ aggregates / variables / inferences or reports which shall be generated by Experian</p>

                </div>
                <div className="content-of-exp-terms">
                    <h2>Credit score</h2>
                    <p>Means the score which shall be mentioned on the Credit Information Report which shall be computed by Experian</p>
                    <p>CICRA shall mean the Credit Information Companies (Regulation) Act, 2005 read with the Credit Information Companies Rules, 2006 and the Credit Information Companies Regulations, 2006, and shall include any other rules and regulations prescribed thereunder.</p>

                </div>
                <div className="content-of-exp-terms">
                    <p>PLEASE READ THE ABOVEMENTIONED TERMS AND CONDITIONS AND CLICK ON “ACCEPT” FOLLOWED BY THE LINK BELOW TO COMPLETE THE AUTHORISATION PROCESS/ FOR SHARING OF YOUR CREDIT INFORMATION BY EXPERIAN WITH CreditHaat IN ITS CAPACITY AS YOUR AUTHORISED REPRESENTATIVE.</p>
                    <p>BY CLICKING “ACCEPT” YOU AGREE AND ACCEPT THE DISCLAIMERS AND TERMS AND CONDITIONS SET OUT HEREIN.</p>
                </div>
                <div className="content-of-exp-terms">
                    <p>** This document is an electronic record in terms of the Information Technology Act, 2000 and Rules made there under, and the amended provisions pertaining to electronic records.</p>

                </div>
            </div>


                    
            <NewHomePageFooter/>
    
    </>
   );
}


export default ExperianTerms;
